#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys
import time
from django.db import connections
import redis
from django.core.management import execute_from_command_line


def check_redis_connection():
    try:
        r = redis.StrictRedis(host=os.getenv('REDIS_HOST',
                                            # '35.197.132.241'
                                             'localhost'
                                            ), port=int(os.getenv('REDIS_PORT', 6379)), db=1)
        r.ping()
        print("‚úÖ Redis connection successful!")
    except redis.ConnectionError as e:
        print("‚ùå Failed to connect to Redis:", e)
        sys.exit(1)


def check_database_connection():
    try:
        # ‡πÄ‡∏ä‡πá‡∏Ñ‡∏Å‡∏≤‡∏£‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏°‡∏ï‡πà‡∏≠‡∏Å‡∏±‡∏ö‡∏ê‡∏≤‡∏ô‡∏Ç‡πâ‡∏≠‡∏°‡∏π‡∏•
        connection = connections['default']
        connection.ensure_connection()
        print("‚úÖ Database connection successful!")
    except Exception as e:
        print("‚ùå Failed to connect to Database:", e)
        sys.exit(1)


def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Backend.settings')
    
    # ‡πÄ‡∏ä‡πá‡∏Ñ‡∏Å‡∏≤‡∏£‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏°‡∏ï‡πà‡∏≠‡∏Å‡πà‡∏≠‡∏ô‡∏ó‡∏µ‡πà Django ‡∏à‡∏∞‡πÄ‡∏£‡∏¥‡πà‡∏°‡∏ó‡∏≥‡∏á‡∏≤‡∏ô
    print("üîÑ Checking connections...")
    check_database_connection()
    check_redis_connection()

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
